// Created by Crowbar 0.42.0.0

$ModelName "C:\Documents and Settings\JR\My Documents\My Manical Creations\P"

$BodyGroup "lifepreserver"
{
	studio "lifepreserver_reference.smd"
}



$TextureGroup "skinfamilies"
{
	{ "lifepreserver.bmp" }
}

$CBox 0 0 0 0 0 0

$BBox 0 0 0 0 0 0

$HBox 0 "Torus01" -17.870001 -17.870001 -4.46 17.870001 17.870001 4.46

$Sequence "blah" {
	"lifepreserver_anims\blah.smd"
	fps 1
}
