// Created by Crowbar 0.42.0.0

$ModelName "C:\Documents and Settings\JR\My Documents\My Manical Creations\P"

$BodyGroup "vikingship"
{
	studio "vikingship_reference.smd"
}



$TextureGroup "skinfamilies"
{
	{ "ship.bmp" "sails.bmp" }
}

$CBox 0 0 0 0 0 0

$BBox 0 0 0 0 0 0

$HBox 0 "Point01" -175.190002 -19.959999 -421.869995 176.800003 509.299988 398.190002

$Sequence "vikingship" {
	"vikingship_anims\vikingship.smd"
	fps 30
	loop
}
