sound/cartoonpirate1.wav
sound/cartoonpirate2.wav
sound/seizurekitty.wav
sprites/guard.spr
sprites/kitty1.spr
sprites/kitty2.spr
sprites/kitty3.spr
sprites/pirate.spr
sprites/tree.spr
sprites/viking.spr
pvk_cartoonb2.cfg
maps/pvk_cartoonb2.res
gfx/env/montagnebk.tga
gfx/env/montagneft.tga
gfx/env/montagnedn.tga
gfx/env/montagnelf.tga
gfx/env/montagnert.tga
gfx/env/montagneup.tga
