sound/explosions/Big.wav
sound/ambient/fire/firebig1.wav
sound/ambient/cave.wav
sound/ambient/hell/horror1.wav
sound/ambient/hell/horror2.wav
sound/ambient/hell/horror3.wav
sound/ambient/hell/horror4.wav
sound/ambient/belltoll_mw.wav
sound/biscuit/c1a3_sci_silo2a.wav
sound/biscuit/c2a3_hg_laugh.wav
sprites/cannon.spr
sprites/glow.spr
sprites/pyramid.spr
sprites/thor.spr
sprites/xffloor.spr
maps/pvk_omni2.res
pvk_omni2.txt
models/thorstatue.mdl
models/palme.mdl
gfx/env/cloudy_bk.tga
gfx/env/cloudy_ft.tga
gfx/env/cloudy_dn.tga
gfx/env/cloudy_lf.tga
gfx/env/cloudy_rt.tga
gfx/env/cloudy_up.tga
