// Created by Crowbar 0.42.0.0

$ModelName "valve/models/uplant3.mdl"

$BodyGroup "studio"
{
	studio "uplant3_reference.smd"
}



$ExternalTextures

$CBox 0 0 0 0 0 0

$BBox 0 0 0 0 0 0

$HBox 0 "Bone03" -5.97 0 -6.55 6.15 9.99 6.06
$HBox 0 "Bone05" -6.4 0 -7.21 6.77 9.96 6.73
$HBox 0 "Bone07" -5.33 0 -5.85 5.52 9.94 5.48
$HBox 0 "Bone09" -3.56 0 -3.99 3.81 9.72 3.66

$Sequence "idle1" {
	"uplant3_anims\idle1.smd"
	fps 13
	loop
}
